seed: 12345
hmm_component: 3

data:
  num_samples: 400

stage1:
  hidden_size: 128
  w: 0.5
  c1: 1.8
  c2: 1.8
  num_particles: 10
  num_iterations: 2

stage2:
  hstage_hidden_size: 64
  w: 0.5
  c1: 1.8
  c2: 1.8
  num_particles: 20
  num_iterations: 2
